"""Write the app's metadata for the Supervisor: ``config.yaml`` and
``translations/en.yaml`` (ARCHITECTURE.md §15.1, §17.1, §17.4; D-123, D-129).

The options, their schema, and the option texts are defined here, next to
the code that validates them (``frame_gallery.config``), so that the files
the Supervisor reads cannot drift from what the app accepts: the department
and period choices come from the built-in vocabulary, and the patterns from
``config.options``. A test keeps both files identical to this output and
checks every offered value against the app's own parser.

    .venv/bin/python scripts/app_config.py           # write both files
    .venv/bin/python scripts/app_config.py --check   # exit 1 if they differ
"""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Final

PROJECT: Final = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT / "src"))

from frame_gallery import __version__  # noqa: E402 - after the path above
from frame_gallery.config.filters import FilterField  # noqa: E402
from frame_gallery.config.vocabulary import BUILTIN_VOCABULARY  # noqa: E402
from frame_gallery.domain import DEFAULT_SOURCE  # noqa: E402

type Value = str | int | list[Value] | dict[str, Value]

CONFIG: Final = PROJECT / "config.yaml"
TRANSLATIONS: Final = PROJECT / "translations" / "en.yaml"
GERMAN_TRANSLATIONS: Final = PROJECT / "translations" / "de.yaml"

TV_HOST_SCHEMA: Final = r"match(^(?:\d{1,3}\.){3}\d{1,3}$)"
BACKGROUND_SCHEMA: Final = r"match(^#[0-9A-Fa-f]{6}$)"
HELPER_SCHEMA: Final = r"match(^(?:input_select|select|input_text)\.[a-z0-9_]{1,64}$)?"
SOURCES: Final = (
    "wikimedia_commons",
    "art_institute_chicago",
    "cleveland_museum_of_art",
    "local_media",
)

HEADER: Final = """\
# Generated by scripts/app_config.py; do not edit (D-123, D-129).
"""


def _choices(field: FilterField) -> list[str]:
    return ["any", *(entry.key for entry in BUILTIN_VOCABULARY.entries_for(field))]


def options() -> dict[str, Value]:
    """The defaults the Supervisor offers (§15.1). ``tv_host`` has none: the
    app cannot start until the user enters it (B1)."""
    return {
        "source": DEFAULT_SOURCE.value,
        "landscape_only": True,
        "strict_tv_format": True,
        "fit_mode": "contain",
    }


def schema() -> dict[str, Value]:
    return {
        "tv_host": TV_HOST_SCHEMA,
        "source": f"list({'|'.join(SOURCES)})",
        "landscape_only": "bool",
        "strict_tv_format": "bool",
        "fit_mode": "list(contain|cover)",
        "department": f"list({'|'.join(_choices(FilterField.DEPARTMENT))})?",
        "style": f"list({'|'.join(_choices(FilterField.STYLE))})?",
        "background_color": BACKGROUND_SCHEMA + "?",
        "source_helper": HELPER_SCHEMA,
        "department_helper": HELPER_SCHEMA,
        "style_helper": HELPER_SCHEMA,
        "color_helper": HELPER_SCHEMA,
        "log_level": "list(info|debug)?",
        "loading_timer": r"match(^timer\.[a-z0-9_]{1,64}$)?",
        "artwork_info_helper": r"match(^input_text\.[a-z0-9_]{1,64}$)?",
        "color": f"list({'|'.join(_choices(FilterField.COLOR))})?",
    }


def config() -> dict[str, Value]:
    """``config.yaml`` (§17.1, D-129). Supervisor pulls the independently
    verified per-architecture release images; its tag is ``version``.
    Experimental is the supported Supervisor lifecycle flag for this beta."""
    return {
        "name": "Frame Gallery \u2013 Samsung Frame TV",
        "version": __version__,
        "slug": "frame_gallery",
        "description": "Samsung Frame TV artwork from museums or your own images.",
        "arch": ["aarch64", "amd64"],
        "image": "ghcr.io/volkue-tech/frame-gallery-ha-{arch}",
        "url": "https://github.com/volkue-tech/frame-gallery-ha",
        "startup": "once",
        "boot": "manual_only",
        "init": False,
        "stage": "experimental",
        "homeassistant": "2026.2.0",
        "homeassistant_api": True,
        "tmpfs": True,
        "timeout": 20,
        "map": [{"type": "media", "read_only": False}],
        "backup_exclude": ["cache/**", "state/quarantine/**", "tv/**"],
        "options": options(),
        "schema": schema(),
    }


HELPER_TEXT: Final = (
    "Optional. An input_select, select, or input_text helper whose state replaces the {what} "
    "option above at every start, for example {example}. A value the helper cannot supply "
    "falls back to the option above, with a warning in the log. Leave empty to use only the "
    "option above."
)


def translations(language: str = "en") -> dict[str, Value]:
    """``translations/en.yaml``: every option's name and description. The
    filter descriptions state which sources each filter applies to (B8)."""
    texts: dict[str, tuple[str, str]] = {
        "tv_host": (
            "TV address",
            (
                "The IPv4 address of your Frame TV on your home network, for example 192.168.1.20. "
                "Only private home-network addresses are accepted. Give the TV a fixed address in "
                "your router (a DHCP reservation), so that it keeps this address."
            ),
        ),
        "source": (
            "Artwork source",
            (
                "wikimedia_commons (default for new installations): 400 curated "
                "near-widescreen artworks; no API key. "
                "art_institute_chicago: Art Institute of Chicago. cleveland_museum_of_art: "
                "Cleveland Museum of Art. local_media: your JPEG/PNG files in "
                "frame_gallery/library in Home Assistant media."
            ),
        ),
        "department": (
            "Department (Cleveland only)",
            (
                "Only works from this department of the Cleveland Museum of Art; any means no "
                "filter. The Art Institute of Chicago and your own images do not support a "
                "department: with them, a department is not applied, and the log and the run "
                "record say so."
                " Wikimedia Commons does not support a department filter either."
            ),
        ),
        "style": (
            "Period (both museums)",
            (
                "Only works created in this period: before 1400, 1400 to 1599, 1600 to 1799, "
                "1800 to 1899, or 1900 and later; any means no filter. It applies to both "
                "museums, not to your own images. Art styles are not offered yet."
                " Wikimedia Commons does not support a period filter either."
            ),
        ),
        "color": (
            "Colour (not available)",
            "No source supports a colour filter yet. Leave any; retained for compatibility only.",
        ),
        "landscape_only": (
            "Landscape only",
            "Only choose artworks that are wider than they are tall.",
        ),
        "strict_tv_format": (
            "Prefer 16:9 (may take longer)",
            (
                "Prefer artworks within about 1 % of the TV's 16:9 shape. If there is none, and "
                "Landscape only is on with the contain fit, another landscape artwork is shown "
                "whole, with margins. Commons sources are within 2.5 % of 16:9; turn this "
                "off to include the whole curated selection rather than prefer the closest matches."
            ),
        ),
        "fit_mode": (
            "Image fit (contain = no crop)",
            (
                "contain shows the whole artwork, with margins where its shape differs from the "
                "TV's (nothing is cropped). cover fills the whole screen and may crop the edges."
            ),
        ),
        "background_color": (
            "Margin colour",
            "The colour of the margins in contain mode, as #RRGGBB; black is #000000.",
        ),
        "source_helper": (
            "Source helper",
            HELPER_TEXT.format(what="Artwork source", example="input_select.frame_gallery_source"),
        ),
        "department_helper": (
            "Department helper",
            HELPER_TEXT.format(what="Department", example="input_select.frame_gallery_department"),
        ),
        "style_helper": (
            "Period helper",
            HELPER_TEXT.format(what="Period", example="input_select.frame_gallery_period"),
        ),
        "color_helper": (
            "Colour helper",
            HELPER_TEXT.format(what="Colour", example="input_select.frame_gallery_colour"),
        ),
        "log_level": (
            "Log detail",
            (
                "Advanced: info (the default) or debug, which also logs each candidate the app "
                "considered."
            ),
        ),
        "loading_timer": (
            "Dashboard loading timer",
            (
                "Optional. This app's dashboard timer, for example timer.frame_gallery_run. "
                "Only this timer is cancelled after cleanup, also on no-match and cancellation. "
                "Leave empty to disable feedback. Its duration remains the crash fail-safe."
            ),
        ),
        "artwork_info_helper": (
            "Dashboard artwork information",
            (
                "Optional. A dedicated Text helper, for example input_text.frame_gallery_artwork, "
                "with minimum length 0, maximum length 255 and no Initial value. The app writes "
                "title, artist and museum for the preview here. Do not use a filter helper. "
                "Leave empty to keep the existing image-only dashboard behavior."
            ),
        ),
    }
    if language == "de":
        texts = {
            "tv_host": (
                "TV-IP-Adresse",
                (
                    "Die feste private IPv4-Adresse deines Frame TV, z. B. 192.168.1.20. "
                    "Reserviere sie im Router; Gerätenamen werden nicht unterstützt."
                ),
            ),
            "source": (
                "Bildquelle",
                (
                    "wikimedia_commons (Standard bei Neuinstallation): 400 ausgewählte "
                    "Werke im breiten Querformat, "
                    "ohne API-Key. art_institute_chicago: Art Institute of Chicago. "
                    "cleveland_museum_of_art: Cleveland Museum of Art. local_media: eigene "
                    "JPEG/PNG-Dateien unter frame_gallery/library im HA-Medienordner."
                ),
            ),
            "landscape_only": (
                "Nur Querformat",
                (
                    "Wählt ausschließlich Bilder aus, die breiter als hoch sind. "
                    "Für einen waagerechten Fernseher empfohlen."
                ),
            ),
            "strict_tv_format": (
                "16:9 bevorzugen (kann länger dauern)",
                (
                    "Sucht zuerst nach fast exakt 16:9. Mit Querformat und contain wird sonst "
                    "ein ganzes Querformat-Bild mit Rand verwendet. Commons liegt höchstens "
                    "2,5 % neben 16:9; ausschalten, um die gesamte Auswahl statt bevorzugt "
                    "der engsten 16:9-Treffer zu nutzen."
                ),
            ),
            "fit_mode": (
                "Bildanpassung (contain = ohne Beschnitt)",
                (
                    "contain zeigt das vollständige Werk mit Rand, ohne es zu beschneiden. "
                    "cover füllt den Bildschirm und kann Ränder abschneiden. Empfehlung: contain."
                ),
            ),
            "department": (
                "Sammlung (nur Cleveland, optional)",
                (
                    "Filtert eine Sammlung des Cleveland Museum of Art. any bedeutet ohne Filter. "
                    "Chicago, Commons und eigene Bilder unterstützen diesen Filter nicht; "
                    "ignorierte Filter werden im Protokoll genannt."
                ),
            ),
            "style": (
                "Entstehungszeit (nur Museen, optional)",
                (
                    "Filtert das Entstehungsjahr in Chicago und Cleveland. any heißt ohne Filter. "
                    "Commons und eigene Bilder unterstützen diesen Filter nicht. "
                    "Kunststile werden noch nicht angeboten."
                ),
            ),
            "background_color": (
                "Randfarbe (optional)",
                "Randfarbe bei contain als #RRGGBB. Ohne Angabe ist der Rand schwarz (#000000).",
            ),
            "source_helper": (
                "Bildquelle vom Dashboard (optional)",
                (
                    "Entitäts-ID eines Dropdown- oder Text-Helfers, z. B. "
                    "input_select.frame_gallery_source. Dessen Wert ersetzt die Bildquelle. "
                    "Leer lassen, um die obige Einstellung zu nutzen."
                ),
            ),
            "department_helper": (
                "Sammlung vom Dashboard (optional)",
                (
                    "Entitäts-ID eines Dropdown- oder Text-Helfers für die Cleveland-Sammlung. "
                    "Leer lassen, um die obige Einstellung zu nutzen."
                ),
            ),
            "style_helper": (
                "Entstehungszeit vom Dashboard (optional)",
                (
                    "Entitäts-ID eines Dropdown- oder Text-Helfers für die Entstehungszeit "
                    "der Museumswerke. Leer lassen, um die obige Einstellung zu nutzen."
                ),
            ),
            "color_helper": (
                "Farb-Helfer (noch nicht verfügbar)",
                (
                    "Kein Farbfilter verfügbar. Leer lassen; nur zur Kompatibilität "
                    "mit bisherigen Einstellungen vorhanden."
                ),
            ),
            "log_level": (
                "Protokolldetails (Expertenoption)",
                (
                    "info ist Standard. debug protokolliert zusätzlich die geprüften Kandidaten. "
                    "Für den normalen Betrieb nicht erforderlich."
                ),
            ),
            "loading_timer": (
                "Dashboard-Ladeanzeige (optional)",
                (
                    "Entitäts-ID des zugehörigen Timers, z. B. timer.frame_gallery_run. "
                    "Die App beendet dessen Ladeanzeige nach dem Aufräumen. "
                    "Ohne Angabe ist der Timer-Ablauf die Absicherung."
                ),
            ),
            "artwork_info_helper": (
                "Künstler und Titel im Dashboard (optional)",
                (
                    "Entitäts-ID eines Text-Helfers, z. B. input_text.frame_gallery_artwork. "
                    "Mindestlänge 0, Maximallänge 255, kein Initialwert. "
                    "Nicht denselben Helfer wie für Filter verwenden. "
                    "Leer lassen für die reine Bildkarte."
                ),
            ),
            "color": (
                "Farbe (noch nicht verfügbar)",
                (
                    "Kein Farbfilter verfügbar. any beibehalten; nur zur Kompatibilität "
                    "mit bisherigen Einstellungen vorhanden."
                ),
            ),
        }
    elif language != "en":
        raise ValueError("unsupported configuration language")
    return {
        "configuration": {
            option: {"name": name, "description": description}
            for option, (name, description) in texts.items()
        }
    }


_PLAIN: Final = re.compile(r"[A-Za-z][A-Za-z0-9_.-]*")
_RESERVED: Final = frozenset({"true", "false", "yes", "no", "on", "off", "null", "y", "n", "~"})


def _scalar(value: str | int) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if _PLAIN.fullmatch(value) and value.lower() not in _RESERVED:
        return value
    return "'" + value.replace("'", "''") + "'"


def _emit(value: Value, indent: int) -> list[str]:
    pad = " " * indent
    lines: list[str] = []
    if isinstance(value, dict):
        for key, item in value.items():
            if isinstance(item, dict | list):
                lines.append(f"{pad}{key}:")
                lines.extend(_emit(item, indent + 2))
            else:
                lines.append(f"{pad}{key}: {_scalar(item)}")
    elif isinstance(value, list):
        for item in value:
            if isinstance(item, dict):
                inner = _emit(item, indent + 2)
                lines.append(f"{pad}- {inner[0].lstrip()}")
                lines.extend(inner[1:])
            elif isinstance(item, list):
                msg = "a list inside a list is not used in these files"
                raise TypeError(msg)
            else:
                lines.append(f"{pad}- {_scalar(item)}")
    return lines


def render(document: dict[str, Value]) -> str:
    return HEADER + "\n".join(_emit(document, 0)) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("--check", action="store_true", help="only compare, write nothing")
    arguments = parser.parse_args(argv)
    differs = []
    for path, document in (
        (CONFIG, config()),
        (TRANSLATIONS, translations()),
        (GERMAN_TRANSLATIONS, translations("de")),
    ):
        text = render(document)
        if arguments.check:
            if not path.exists() or path.read_text() != text:
                differs.append(path.relative_to(PROJECT).as_posix())
        else:
            path.parent.mkdir(exist_ok=True)
            path.write_text(text)
    if differs:
        print("out of date:", ", ".join(differs), file=sys.stderr)  # noqa: T201
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
