"""Write the app's metadata for the Supervisor: ``config.yaml`` and
``translations/en.yaml`` (ARCHITECTURE.md §15.1, §17.1, §17.4; D-123, D-129).

The options, their schema, and the option texts are defined here, next to
the code that validates them (``frame_gallery.config``), so that the files
the Supervisor reads cannot drift from what the app accepts: the department
and period choices come from the built-in vocabulary, and the patterns from
``config.options``. A test keeps both files identical to this output and
checks every offered value against the app's own parser.

    .venv/bin/python scripts/app_config.py           # write both files
    .venv/bin/python scripts/app_config.py --check   # exit 1 if they differ
"""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Final

PROJECT: Final = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT / "src"))

from frame_gallery import __version__  # noqa: E402 - after the path above
from frame_gallery.config.filters import FilterField  # noqa: E402
from frame_gallery.config.vocabulary import BUILTIN_VOCABULARY  # noqa: E402

type Value = str | int | list[Value] | dict[str, Value]

CONFIG: Final = PROJECT / "config.yaml"
TRANSLATIONS: Final = PROJECT / "translations" / "en.yaml"

TV_HOST_SCHEMA: Final = r"match(^(?:\d{1,3}\.){3}\d{1,3}$)"
BACKGROUND_SCHEMA: Final = r"match(^#[0-9A-Fa-f]{6}$)"
HELPER_SCHEMA: Final = r"match(^(?:input_select|select|input_text)\.[a-z0-9_]{1,64}$)?"
SOURCES: Final = (
    "art_institute_chicago",
    "cleveland_museum_of_art",
    "local_media",
    "wikimedia_commons",
)

HEADER: Final = """\
# Generated by scripts/app_config.py; do not edit (D-123, D-129).
"""


def _choices(field: FilterField) -> list[str]:
    return ["any", *(entry.key for entry in BUILTIN_VOCABULARY.entries_for(field))]


def options() -> dict[str, Value]:
    """The defaults the Supervisor offers (§15.1). ``tv_host`` has none: the
    app cannot start until the user enters it (B1)."""
    return {
        "source": "art_institute_chicago",
        "department": "any",
        "style": "any",
        "color": "any",
        "landscape_only": True,
        "strict_tv_format": True,
        "fit_mode": "contain",
        "background_color": "#000000",
    }


def schema() -> dict[str, Value]:
    return {
        "tv_host": TV_HOST_SCHEMA,
        "source": f"list({'|'.join(SOURCES)})",
        "department": f"list({'|'.join(_choices(FilterField.DEPARTMENT))})",
        "style": f"list({'|'.join(_choices(FilterField.STYLE))})",
        "color": f"list({'|'.join(_choices(FilterField.COLOR))})",
        "landscape_only": "bool",
        "strict_tv_format": "bool",
        "fit_mode": "list(contain|cover)",
        "background_color": BACKGROUND_SCHEMA,
        "source_helper": HELPER_SCHEMA,
        "department_helper": HELPER_SCHEMA,
        "style_helper": HELPER_SCHEMA,
        "color_helper": HELPER_SCHEMA,
        "log_level": "list(info|debug)?",
        "loading_timer": r"match(^timer\.[a-z0-9_]{1,64}$)?",
        "artwork_info_helper": r"match(^input_text\.[a-z0-9_]{1,64}$)?",
    }


def config() -> dict[str, Value]:
    """``config.yaml`` (§17.1, D-129). Supervisor pulls the independently
    verified per-architecture release images; its tag is ``version``.
    Experimental is the supported Supervisor lifecycle flag for this beta."""
    return {
        "name": "Frame Gallery \u2013 Samsung Frame TV",
        "version": __version__,
        "slug": "frame_gallery",
        "description": "Samsung Frame TV artwork from museums or your own images.",
        "arch": ["aarch64", "amd64"],
        "image": "ghcr.io/volkue-tech/frame-gallery-ha-{arch}",
        "url": "https://github.com/volkue-tech/frame-gallery-ha",
        "startup": "once",
        "boot": "manual_only",
        "init": False,
        "stage": "experimental",
        "homeassistant": "2026.2.0",
        "homeassistant_api": True,
        "tmpfs": True,
        "timeout": 20,
        "map": [{"type": "media", "read_only": False}],
        "backup_exclude": ["cache/**", "state/quarantine/**", "tv/**"],
        "options": options(),
        "schema": schema(),
    }


HELPER_TEXT: Final = (
    "Optional. An input_select, select, or input_text helper whose state replaces the {what} "
    "option above at every start, for example {example}. A value the helper cannot supply "
    "falls back to the option above, with a warning in the log. Leave empty to use only the "
    "option above."
)


def translations() -> dict[str, Value]:
    """``translations/en.yaml``: every option's name and description. The
    filter descriptions state which sources each filter applies to (B8)."""
    texts: dict[str, tuple[str, str]] = {
        "tv_host": (
            "TV address",
            (
                "The IPv4 address of your Frame TV on your home network, for example 192.168.1.20. "
                "Only private home-network addresses are accepted. Give the TV a fixed address in "
                "your router (a DHCP reservation), so that it keeps this address."
            ),
        ),
        "source": (
            "Artwork source",
            (
                "Where the artwork comes from: the Art Institute of Chicago (public-domain "
                "works), the Cleveland Museum of Art (open-access works), Wikimedia Commons "
                "(50 curated modern landscape artworks, no API key), or local_media, your "
                "own JPEG and PNG images in the folder frame_gallery/library of Home Assistant's "
                "media."
            ),
        ),
        "department": (
            "Department (Cleveland only)",
            (
                "Only works from this department of the Cleveland Museum of Art; any means no "
                "filter. The Art Institute of Chicago and your own images do not support a "
                "department: with them, a department is not applied, and the log and the run "
                "record say so."
                " Wikimedia Commons does not support a department filter either."
            ),
        ),
        "style": (
            "Period (both museums)",
            (
                "Only works created in this period: before 1400, 1400 to 1599, 1600 to 1799, "
                "1800 to 1899, or 1900 and later; any means no filter. It applies to both "
                "museums, not to your own images. Art styles are not offered yet."
                " Wikimedia Commons does not support a period filter either."
            ),
        ),
        "color": (
            "Colour",
            "No source supports a colour filter yet, so the only choice is any.",
        ),
        "landscape_only": (
            "Landscape only",
            "Only choose artworks that are wider than they are tall.",
        ),
        "strict_tv_format": (
            "Prefer the TV's shape",
            (
                "Prefer artworks within about 1 % of the TV's 16:9 shape. If there is none, and "
                "Landscape only is on with the contain fit, another landscape artwork is shown "
                "whole, with margins."
            ),
        ),
        "fit_mode": (
            "Fit",
            (
                "contain shows the whole artwork, with margins where its shape differs from the "
                "TV's (nothing is cropped). cover fills the whole screen and may crop the edges."
            ),
        ),
        "background_color": (
            "Margin colour",
            "The colour of the margins in contain mode, as #RRGGBB; black is #000000.",
        ),
        "source_helper": (
            "Source helper",
            HELPER_TEXT.format(what="Artwork source", example="input_select.frame_gallery_source"),
        ),
        "department_helper": (
            "Department helper",
            HELPER_TEXT.format(what="Department", example="input_select.frame_gallery_department"),
        ),
        "style_helper": (
            "Period helper",
            HELPER_TEXT.format(what="Period", example="input_select.frame_gallery_period"),
        ),
        "color_helper": (
            "Colour helper",
            HELPER_TEXT.format(what="Colour", example="input_select.frame_gallery_colour"),
        ),
        "log_level": (
            "Log detail",
            (
                "Advanced: info (the default) or debug, which also logs each candidate the app "
                "considered."
            ),
        ),
        "loading_timer": (
            "Dashboard loading timer",
            (
                "Optional. This app's dashboard timer, for example timer.frame_gallery_run. "
                "Only this timer is cancelled after cleanup, also on no-match and cancellation. "
                "Leave empty to disable feedback. Its duration remains the crash fail-safe."
            ),
        ),
        "artwork_info_helper": (
            "Dashboard artwork information",
            (
                "Optional. A dedicated Text helper, for example input_text.frame_gallery_artwork, "
                "with minimum length 0, maximum length 255 and no Initial value. The app writes "
                "title, artist and museum for the preview here. Do not use a filter helper. "
                "Leave empty to keep the existing image-only dashboard behavior."
            ),
        ),
    }
    return {
        "configuration": {
            option: {"name": name, "description": description}
            for option, (name, description) in texts.items()
        }
    }


_PLAIN: Final = re.compile(r"[A-Za-z][A-Za-z0-9_.-]*")
_RESERVED: Final = frozenset({"true", "false", "yes", "no", "on", "off", "null", "y", "n", "~"})


def _scalar(value: str | int) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if _PLAIN.fullmatch(value) and value.lower() not in _RESERVED:
        return value
    return "'" + value.replace("'", "''") + "'"


def _emit(value: Value, indent: int) -> list[str]:
    pad = " " * indent
    lines: list[str] = []
    if isinstance(value, dict):
        for key, item in value.items():
            if isinstance(item, dict | list):
                lines.append(f"{pad}{key}:")
                lines.extend(_emit(item, indent + 2))
            else:
                lines.append(f"{pad}{key}: {_scalar(item)}")
    elif isinstance(value, list):
        for item in value:
            if isinstance(item, dict):
                inner = _emit(item, indent + 2)
                lines.append(f"{pad}- {inner[0].lstrip()}")
                lines.extend(inner[1:])
            elif isinstance(item, list):
                msg = "a list inside a list is not used in these files"
                raise TypeError(msg)
            else:
                lines.append(f"{pad}- {_scalar(item)}")
    return lines


def render(document: dict[str, Value]) -> str:
    return HEADER + "\n".join(_emit(document, 0)) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("--check", action="store_true", help="only compare, write nothing")
    arguments = parser.parse_args(argv)
    differs = []
    for path, document in ((CONFIG, config()), (TRANSLATIONS, translations())):
        text = render(document)
        if arguments.check:
            if not path.exists() or path.read_text() != text:
                differs.append(path.relative_to(PROJECT).as_posix())
        else:
            path.parent.mkdir(exist_ok=True)
            path.write_text(text)
    if differs:
        print("out of date:", ", ".join(differs), file=sys.stderr)  # noqa: T201
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
