"""Write the container image's requirement files from the lock (D-128, D-130, D-142).

The image's Python is Alpine's CPython 3.14 on musl, for ``aarch64`` and
``amd64`` (Phase 6). For every package that the image installs, this picks
from ``uv.lock`` the one wheel that pip installs on each of the two
platforms, and writes it with its hash:

* ``requirements/image-runtime.txt``: the app's runtime packages;
* ``requirements/image-test.txt``: the test tools of the container's test
  stage (pytest, pytest-cov, and coverage, with their dependencies).

The image installs exactly these files, hash-checked, as binary wheels only,
and without resolving dependencies again (the lock has resolved them). Each
requirement lists the chosen wheel files in a comment above it.

    .venv/bin/python scripts/image_requirements.py           # write both files
    .venv/bin/python scripts/image_requirements.py --check   # exit 1 if they differ
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final

from packaging.markers import Marker
from packaging.tags import Tag, compatible_tags, cpython_tags
from packaging.utils import canonicalize_name, parse_wheel_filename

PROJECT: Final = Path(__file__).resolve().parents[1]
LOCK: Final = PROJECT / "uv.lock"
PROJECT_NAME: Final = "frame-gallery"
PYTHON: Final = (3, 14)
ARCHITECTURES: Final = ("aarch64", "x86_64")
MUSL_MINORS: Final = (2, 1, 0)
TEST_ROOTS: Final = ("pytest", "pytest-cov")

OUTPUTS: Final = {
    "runtime": PROJECT / "requirements" / "image-runtime.txt",
    "test": PROJECT / "requirements" / "image-test.txt",
}

HEADER: Final = """\
# Generated by scripts/image_requirements.py from uv.lock; do not edit.
# {what}
# CPython 3.14 on musllinux_1_2, aarch64 and x86_64: one binary wheel per
# platform, hash-checked (D-128, D-130, D-142).
"""


@dataclass(frozen=True, slots=True)
class Wheel:
    name: str
    version: str
    filename: str
    url: str
    sha256: str


def _tags(architecture: str) -> list[Tag]:
    """The tags pip accepts for CPython 3.14 on musl, best first."""
    platforms = [f"musllinux_1_{minor}_{architecture}" for minor in MUSL_MINORS]
    abi = f"cp{PYTHON[0]}{PYTHON[1]}"
    return [
        *cpython_tags(PYTHON, [abi], platforms),
        *compatible_tags(PYTHON, abi, platforms),
    ]


def _environment(architecture: str) -> dict[str, str]:
    return {
        "implementation_name": "cpython",
        "platform_python_implementation": "CPython",
        "platform_machine": architecture,
        "platform_system": "Linux",
        "sys_platform": "linux",
        "os_name": "posix",
        "python_version": f"{PYTHON[0]}.{PYTHON[1]}",
        "python_full_version": f"{PYTHON[0]}.{PYTHON[1]}.0",
        "extra": "",
    }


def _applies(entry: Mapping[str, Any], architecture: str) -> bool:
    marker = entry.get("marker")
    return marker is None or Marker(marker).evaluate(_environment(architecture))


def _closure(
    packages: Mapping[str, Mapping[str, Any]], roots: Iterable[str], architecture: str
) -> set[str]:
    """Every package that ``roots`` need on ``architecture``, roots included."""
    found: set[str] = set()
    pending = [canonicalize_name(root) for root in roots]
    while pending:
        name = pending.pop()
        if name in found:
            continue
        found.add(name)
        pending.extend(
            canonicalize_name(dependency["name"])
            for dependency in packages[name].get("dependencies", ())
            if _applies(dependency, architecture)
        )
    return found


def _project_roots(packages: Mapping[str, Mapping[str, Any]], architecture: str) -> list[str]:
    project = packages[PROJECT_NAME]
    return [
        dependency["name"]
        for dependency in project.get("dependencies", ())
        if _applies(dependency, architecture)
    ]


def _best_wheel(package: Mapping[str, Any], architecture: str) -> Wheel:
    ranking = {tag: rank for rank, tag in enumerate(_tags(architecture))}
    best: tuple[int, Wheel] | None = None
    for wheel in package.get("wheels", ()):
        filename = wheel["url"].rsplit("/", 1)[1]
        _, _, _, tags = parse_wheel_filename(filename)
        rank = min((ranking[tag] for tag in tags if tag in ranking), default=None)
        if rank is None:
            continue
        algorithm, _, digest = wheel["hash"].partition(":")
        if algorithm != "sha256":
            msg = f"{filename}: unexpected hash algorithm {algorithm}"
            raise ValueError(msg)
        candidate = Wheel(package["name"], package["version"], filename, wheel["url"], digest)
        if best is None or rank < best[0]:
            best = (rank, candidate)
    if best is None:
        msg = f"{package['name']} has no wheel for CPython 3.14 on musl {architecture}"
        raise ValueError(msg)
    return best[1]


def load_packages(lock: Path = LOCK) -> dict[str, Mapping[str, Any]]:
    document = tomllib.loads(lock.read_text())
    return {canonicalize_name(package["name"]): package for package in document["package"]}


def selected_wheels(packages: Mapping[str, Mapping[str, Any]], kind: str) -> dict[str, list[Wheel]]:
    """``{package: [wheel for each architecture]}`` for ``kind``
    (``runtime`` or ``test``), sorted by package name."""
    chosen: dict[str, list[Wheel]] = {}
    for architecture in ARCHITECTURES:
        roots = _project_roots(packages, architecture) if kind == "runtime" else list(TEST_ROOTS)
        for name in sorted(_closure(packages, roots, architecture)):
            wheel = _best_wheel(packages[name], architecture)
            wheels = chosen.setdefault(name, [])
            if wheel not in wheels:
                wheels.append(wheel)
    return dict(sorted(chosen.items()))


def render(wheels: Mapping[str, Sequence[Wheel]], kind: str) -> str:
    what = (
        "The container image's runtime packages."
        if kind == "runtime"
        else "The test tools of the container's test stage (never in the app image)."
    )
    lines = [HEADER.format(what=what)]
    for name, chosen in wheels.items():
        lines.extend(f"# {wheel.filename}" for wheel in chosen)
        lines.append(f"{name}=={chosen[0].version} \\")
        hashes = [f"    --hash=sha256:{wheel.sha256}" for wheel in chosen]
        lines.append(" \\\n".join(hashes))
    return "\n".join(lines) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("--check", action="store_true", help="only compare, write nothing")
    arguments = parser.parse_args(argv)
    packages = load_packages()
    differs = []
    for kind, path in OUTPUTS.items():
        text = render(selected_wheels(packages, kind), kind)
        if arguments.check:
            if not path.exists() or path.read_text() != text:
                differs.append(path.relative_to(PROJECT).as_posix())
        else:
            path.write_text(text)
    if differs:
        print("out of date with uv.lock:", ", ".join(differs), file=sys.stderr)  # noqa: T201
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
